version: '3.8'

services:
  speedtest-tracker:
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    container_name: speedtest
    restart: unless-stopped
    networks:
      - common-network
    ports:
      - '8080:80'
      - '6443:443'
    environment:
      PUID: 1000
      PGID: 1000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME : ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TIME_ZONE}
    volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - config:/config
        - web:/etc/ssl/web

networks:
  common-network:
    external: true

volumes:
  config:
  web: