version: "3.8"
x-pihole-template: &pihole
  image: pihole/pihole:latest
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "8085:80/tcp"
  environment:
    TZ: ${TIME_ZONE}
    WEBPASSWORD: ${PIHOLE_PASSWORD}
    DNS1: ${DNS_IP}
  cap_add:
    - NET_ADMIN
  restart: unless-stopped

services:
  pihole-guest:
    <<: *pihole
    container_name: pihole-guest
    hostname: pihole-guest
    networks:
      pihole_ipvlan:
        ipv4_address: 192.168.10.3
    volumes:
      - guest_pihole_data:/etc/pihole
      - guest_dnsmasq_data:/etc/dnsmasq.d

  pihole-home:
    <<: *pihole
    container_name: pihole-home
    hostname: pihole-home
    networks:
      pihole_ipvlan:
        ipv4_address: 192.168.10.4
    volumes:
      - home_pihole_data:/etc/pihole
      - home_dnsmasq_data:/etc/dnsmasq.d

networks:
  pihole_ipvlan:
    external: true

volumes:
  guest_pihole_data:
  guest_dnsmasq_data:
  home_pihole_data:
  home_dnsmasq_data:
