version: "3.8"
x-pihole-template: &pihole
  image: pihole/pihole:latest
  ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "8085:80/tcp"
  environment:
    TZ: ${TIME_ZONE}
    WEBPASSWORD: ${PIHOLE_PASSWORD}
    DNS1: 192.168.10.3
  cap_add:
    - NET_ADMIN
  restart: unless-stopped

services:
  pihole-personal:
    <<: *pihole
    container_name: pihole-personal
    hostname: pihole-personal
    networks:
      ipvlan0:
        ipv4_address: 192.168.10.4
    volumes:
      - '${PIHOLE_PERSONAL_DATA}/etc-pihole:/etc/pihole'
      - '${PIHOLE_PERSONAL_DATA}/etc-dnsmasq.d:/etc/dnsmasq.d'

  pihole-cam-iot:
    <<: *pihole
    container_name: pihole-cam-iot
    hostname: pihole-cam-iot
    networks:
      ipvlan0:
        ipv4_address: 192.168.10.5
    volumes:
      - '${PIHOLE_CAM_IOT_DATA}/etc-pihole:/etc/pihole'
      - '${PIHOLE_CAM_IOT_DATA}/etc-dnsmasq.d:/etc/dnsmasq.d'

  pihole-guest:
    <<: *pihole
    container_name: pihole-guest
    hostname: pihole-guest
    networks:
      ipvlan0:
        ipv4_address: 192.168.10.6
    volumes:
      - '${PIHOLE_GUEST_DATA}/etc-pihole:/etc/pihole'
      - '${PIHOLE_GUEST_DATA}/etc-dnsmasq.d:/etc/dnsmasq.d'

  pihole-home:
    <<: *pihole
    container_name: pihole-home
    hostname: pihole-home
    networks:
      ipvlan0:
        ipv4_address: 192.168.10.7
    volumes:
      - '${PIHOLE_HOME_DATA}/etc-pihole:/etc/pihole'
      - '${PIHOLE_HOME_DATA}/etc-dnsmasq.d:/etc/dnsmasq.d'

networks:
  ipvlan0:
    external: true
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l3
      parent: eno1

    ipam:
      config:
        - subnet: 192.168.10.0/24
