version: "3.8"
services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      pihole_ipvlan:
        ipv4_address: 192.168.10.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf
    restart: unless-stopped

networks:
  pihole_ipvlan:
    name: pihole_ipvlan
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l3
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.10.0/24
